### ISSUE TITLE
A switches view

### ISSUE THREAD

**Issue by patricoferris** [tarides/meio#26]
Presumably this is possible to see what is attached to a given switch, not quite sure on the UI for this but I think it might be useful information to expose to the end user.

**Comment by TheLortex** [comment]
I found that the hard part with switches (and cancellation contexts in general) is that fibers move around cancellation contexts, so it's hard to know what's going on. 
In particular a fiber might create a cancellation context, moving inside, do some stuff and then move outside. Stats will be aggregated for the fiber so we won't know what was happening inside the cancellation context. I'm thinking about adding an "implicit" fiber for each cancellation context, so that it fits a higher level mental model.

**Comment by TheLortex** [comment]
Fixed by https://github.com/tarides/meio/pull/47
